### ISSUE TITLE
Unsupported ops: aten::remainder, aten::where

### ISSUE THREAD

**Issue by AlexMinhao** [alibaba/TinyNeuralNetwork#28] opened 2022-01-19 09:21 UTC
Thanks for your excellent work. when converting the model from Pytorch to TFLite, it does not support the following operations:
ERROR (TinyNeuralNetwork.tinynn.converter.base) **Unsupported ops: aten::remainder, aten::where**
Hope you can support these ops later. Thanks.

**Comment by peterjc123** [comment] 2022-01-19 10:57
@AlexMinhao Will take a look. Stay tuned.

**Comment by peterjc123** [comment] 2022-01-19 11:11
@AlexMinhao Are you using those ops to generate a variable tensor or a constant tensor? `aten::where(cond, x, y)` can be interpreted as `y.masked_fill(cond, x)`, but I cannot find a replacement for `aten::remainder` with the float input tensors.

**Comment by peterjc123** [comment] 2022-01-19 13:33
@AlexMinhao These ops are supported with https://github.com/alibaba/TinyNeuralNetwork/commit/4120228c070ab3eab00a1ebdd3ae2c8f3562d4d9. Please have a try.

**Comment by peterjc123** [comment] 2022-01-25 02:25
I'll close this issue for now since those ops are supported. Please have a try when you have time.

**Closed by peterjc123** 2022-01-25 02:25 UTC
Labels: enhancement

**Comment by AlexMinhao** [comment] 2022-01-27 09:16
Thanks a lot! Got it!

BTW. When using the torch.divide, I got too many warnings on win10. Is it a serious problem?

UserWarning: Non constant node removed, something must be wrong there
  warnings.warn('Non constant node removed, something must be wrong there')
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node:
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 5060, {'node_type': 22, 'outputs': ['86'], 'label': 'Reshape', 'name': '__tinynn_op_3122__', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.ReshapeOperator object at 0x000001F8875867F0>})
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node:
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 5062, {'node_type': 22, 'outputs': ['89'], 'label': 'Reshape', 'name': '__tinynn_op_3123__', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.ReshapeOperator object at 0x000001F8875868E0>})
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node:
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 1921, {'node_type': 42, 'outputs': ['80'], 'label': 'Div', 'name': '__tinynn_op_3118__', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.DivOperator object at 0x000001F88757DF70>})
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node:
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 1923, {'node_type': 36, 'outputs': ['86_transform'], 'label': 'Gather', 'name': '__tinynn_op_3121__', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.GatherOperator object at 0x000001F887586550>})
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node:
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 1919, {'node_type': 22, 'outputs': ['78'], 'label': 'Reshape', 'name': '__tinynn_op_3117__', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.ReshapeOperator object at 0x000001F88757DD30>})
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node:
WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 1917, {'node_type': 36, 'outputs': ['78_transform'], 'label': 'Gather', 'name': '__tinynn_op_3116__', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.GatherOperator object at 0x000001F88757DAF0>})

**Comment by peterjc123** [comment] 2022-01-27 13:15
> 

This message reveals the fact that the graph optimizer tries to optimize away a lot of unused nodes, which indicates that maybe an incomplete graph is generated.

**Comment by peterjc123** [comment] 2022-01-28 03:58
> Thanks a lot! Got it!
> 
> BTW. When using the torch.divide, I got too many warnings on win10. Is it a serious problem?
> 
> UserWarning: Non constant node removed, something must be wrong there warnings.warn('Non constant node removed, something must be wrong there') WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------ WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node: WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 5060, {'node_type': 22, 'outputs': ['86'], 'label': 'Reshape', 'name': '**tinynn_op_3122**', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.ReshapeOperator object at 0x000001F8875867F0>}) WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------ WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node: WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 5062, {'node_type': 22, 'outputs': ['89'], 'label': 'Reshape', 'name': '**tinynn_op_3123**', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.ReshapeOperator object at 0x000001F8875868E0>}) WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------ WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node: WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 1921, {'node_type': 42, 'outputs': ['80'], 'label': 'Div', 'name': '**tinynn_op_3118**', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.DivOperator object at 0x000001F88757DF70>}) WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------ WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node: WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 1923, {'node_type': 36, 'outputs': ['86_transform'], 'label': 'Gather', 'name': '**tinynn_op_3121**', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.GatherOperator object at 0x000001F887586550>}) WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------ WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node: WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 1919, {'node_type': 22, 'outputs': ['78'], 'label': 'Reshape', 'name': '**tinynn_op_3117**', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.ReshapeOperator object at 0x000001F88757DD30>}) WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) ------------------------------ WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) Info of the deleted node: WARNING (TinyNeuralNetwork.tinynn.converter.operators.optimize) vertex: igraph.Vertex(<igraph.Graph object at 0x000001F8E9E2E130>, 1917, {'node_type': 36, 'outputs': ['78_transform'], 'label': 'Gather', 'name': '**tinynn_op_3116**', 'op': <TinyNeuralNetwork.tinynn.converter.operators.tflite.generated_ops.GatherOperator object at 0x000001F88757DAF0>})

It seems that the problem is caused by the following code block. It would be good to know how it is written in Python.
```py
  %130 : Tensor = aten::slice(%preds_torch.1, %44, %44, %104, %26) # i:\project\mmpose_0.22.0\mmpose\mmpose\models\detectors\top_down.py:212:0
  %132 : Tensor = aten::slice(%130, %26, %44, %104, %26) # i:\project\mmpose_0.22.0\mmpose\mmpose\models\detectors\top_down.py:212:0
  %134 : Tensor = aten::select(%132, %78, %26) # i:\project\mmpose_0.22.0\mmpose\mmpose\models\detectors\top_down.py:212:0
  %137 : Tensor = aten::copy_(%134, %128, %13) # i:\project\mmpose_0.22.0\mmpose\mmpose\models\detectors\top_down.py:212:0
```
