### ISSUE TITLE
torch.fx

### ISSUE THREAD

**Issue by Cydia2018** [alibaba/TinyNeuralNetwork#10] opened 2021-11-26 09:08 UTC
可否与torch的新特性fx结合，为量化、剪枝提供新的解决方法。

**Comment by peterjc123** [comment] 2021-11-26 09:46
Duplicate of https://github.com/alibaba/TinyNeuralNetwork/issues/4. The integration with FX is not our top priority at present, but we will look into it at a reasonable time in the future.

**Closed** 2021-12-15 09:49 UTC
Labels: question
