### ISSUE TITLE
[tracer] code generating failed when trying to load a model generated using legacy PyTorch

### ISSUE THREAD

**Issue by Raychen0617** [alibaba/TinyNeuralNetwork#104] opened 2022-08-10 03:11 UTC
Hi, I am wondering if the qat method can work on the yolov5 model. When trying to convert yolov5 to a quantized model, I met some errors when executing the following code. Thanks for helping !!

Code: 
```
from tinynn.graph.quantization.quantizer import QATQuantizer
quantizer = QATQuantizer(model, dummy_input=torch.rand(1,3,640,640).to(device), work_dir='./quantization', config={'asymmetric': True, 'per_tensor': True})
model = quantizer.quantize()
```

Error
```
torch/nn/modules/module.py", line 1208, in __getattr_type(self).__name__, name))
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
```

### Environment: 
pytorch: 1.12.1
python: 3.7.13
cuda:11.6

**Comment by peterjc123** [comment] 2022-08-10 03:15
This issue is related to your training framework. Obviously, you have your own implementation of the class `Upsample`. I'd be glad to look into it if you can tell me which repo are you using.

**Comment by peterjc123** [comment] 2022-08-10 03:20
Would you please share the generated script under the `./quantization` folder?

**Comment by peterjc123** [comment] 2022-08-10 03:25
As can be seen in the [code](https://github.com/pytorch/pytorch/blob/v1.12.1/torch/nn/modules/upsampling.py#L150), `recompute_scale_factor` is actually an attribute of the class `Upsample`. So, it is possibly caused by a corrupted PyTorch installation?

**Comment by Raychen0617** [comment] 2022-08-10 03:49
Thanks for helping, I would try to downgrade my PyTorch version and try again. This is the generated file [model_qat.zip](https://github.com/alibaba/TinyNeuralNetwork/files/9296416/model_qat.zip)

**Comment by peterjc123** [comment] 2022-08-10 03:55
> Thanks for helping, I would try to downgrade my PyTorch version and try again. This is the generated file [model_qat.zip](https://github.com/alibaba/TinyNeuralNetwork/files/9296416/model_qat.zip)

Well, I mean the python script, not the weights file.

**Comment by Raychen0617** [comment] 2022-08-10 05:19
Sorry about that. In fact, the code did not generate any script file under `./quantization` folder.  It stucks at the generate code step

```
Traceback (most recent call last):
  File "yolo_quantize.py", line 674, in <module>
    main(opt)
  File "yolo_quantize.py", line 569, in main
    train(opt.hyp, opt, device, callbacks)
  File "yolo_quantize.py", line 187, in train
    model = quantizer.quantize()
  File "/home/urchinwang/anaconda3/envs/py3.7/lib/python3.7/site-packages/tinynn/graph/quantization/quantizer.py", line 221, in quantize
    graph.generate_code(model_code_path, model_weights_path, model_name_qat)
  File "/home/urchinwang/anaconda3/envs/py3.7/lib/python3.7/site-packages/tinynn/graph/tracer.py", line 1951, in generate_code
    init_block = self.__gen_init_code()
  File "/home/urchinwang/anaconda3/envs/py3.7/lib/python3.7/site-packages/tinynn/graph/tracer.py", line 1824, in __gen_init_code
    orig_constructor_line, mod_cache = gen_module_constrctor_line(node.module, mod_cache_dict)
  File "/home/urchinwang/anaconda3/envs/py3.7/lib/python3.7/site-packages/tinynn/graph/tracer.py", line 1246, in gen_module_constrctor_line
    prop_value = getattr(module, prop_name)
  File "/home/urchinwang/anaconda3/envs/py3.7/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1208, in __getattr__
    type(self).__name__, name))
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
```

In addition, I met a problem before this one and modified PyTorch source code as the link specified [ https://github.com/openai/DALL-E/issues/54#issuecomment-1092826376](url), I am not sure whether this modification causes this error

**Comment by peterjc123** [comment] 2022-08-10 06:34
@Raychen0617 Okay, I think I know the reason. It is because you are loading from a serialized model in a newer version of PyTorch, which is generated using an old version of PyTorch, but the current version of PyTorch contains the property `recompute_scale_factor`. I guess we can skip this kind of property or loading the default value from the constructor.

**Comment by peterjc123** [comment] 2022-08-10 06:44
@Raychen0617 Should be resolved via https://github.com/alibaba/TinyNeuralNetwork/commit/c3fa67cda8685202f76f2dcf960d84b077cc0d40

**Comment by peterjc123** [comment] 2022-08-10 06:50
> In addition, I met a problem before this one and modified PyTorch source code as the link specified [ https://github.com/openai/DALL-E/issues/54#issuecomment-1092826376](url), I am not sure whether this modification causes this error

Also, the workaround in that post is not that graceful. The following seems a better solution.
```py
for m in model.modules():
    if isinstance(m, nn.Upsample):
        setattr(m, 'recompute_scale_factor', None)
```

**Comment by Raychen0617** [comment] 2022-08-10 07:52
This solves the problem, thanks a lot !!!

**Closed** 2022-08-10 08:57 UTC
Labels: enhancement, awaiting response
