### ISSUE TITLE
For an int8 QAT model, the dequantized weights/bias are different from the original model

### ISSUE THREAD

**Issue by liamsun2019** [alibaba/TinyNeuralNetwork#20] opened 2021-12-20 01:48 UTC
Hi, sorry to bother. This issue may not be directly related to tinynn. The scenario on my side is described as following:
1. I perform int8 QAT based on an official float32 model.
2. Only to fine tune some layers, I set requires_grad to False for all the other layers.
3. The training goes normally and the conversion to tflite is also done.
4. Use tf2onnx to dequantize the generated tflite and check the weights/bias. The weights/bias of the frozen layers are pretty different compared to the original model.

My target is to keep the weights/bias the same with the original  model for the frozen layers after dequantization. Not sure if it's feasible. As you know, the official float32 model performs well for most cases and I just want to fine tune a few layers. Meanwhile, considering the inference speed on some edge devices, I have to perform QAT since the post-training quantization is really worse.

Thanks for your time.

**Comment by dinghuanghao** [comment] 2021-12-20 03:24
For example, in the BN layer, even if requires_grad is false, the internal statistical variables(running_mean, running_var) will still change. You must set layer.eval(). You can add this and try again.

**Comment by liamsun2019** [comment] 2021-12-20 04:51
Actually, I tried the approach you just mentioned but the situation remained unchanged, i,e the weights/bias are different after dequantization. Is there an alternative way to achieve that? Thanks.

**Comment by dinghuanghao** [comment] 2021-12-20 06:33
After calling our quantizer, a quantized model code will be generated. You need to move the operators that do not need to be quantized outside of QuantStub() and DeQuantStub()

**Comment by dinghuanghao** [comment] 2021-12-20 06:33
def forward(self, input_1):
        fake_quant_0 = self.fake_quant_0(input_1)
        model_0_0 = self.model_0_0(fake_quant_0)

**Comment by dinghuanghao** [comment] 2021-12-20 06:36
-----------before-----------  
  def forward(self, input_1):
        fake_quant_0 = self.fake_quant_0(input_1) # quantize
        model_0_0 = self.model_0_0(fake_quant_0) # qat
        model_0_1 = self.model_0_1(model_0_0) # qat
        model_0_2 = self.model_0_2(model_0_1) # qat
        model_1_0 = self.model_1_0(model_0_2) # qat
        fake_dequant_0 = self.fake_dequant_0(model_1_0)  # dequantize


---------after-------------
  def forward(self, input_1):

        model_0_0 = self.model_0_0(input_1)   # float32
        fake_quant_0 = self.fake_quant_0(model_0_0) # quantize
        model_0_1 = self.model_0_1(fake_quant_0) # qat
        model_0_2 = self.model_0_2(model_0_1) # qat
        model_1_0 = self.model_1_0(model_0_2) # qat
        fake_dequant_0 = self.fake_dequant_0(model_1_0) # dequantize

**Comment by liamsun2019** [comment] 2021-12-20 06:46
Thanks for your suggestions. Based on your sample, my understanding is that, except the layers that need to be fine-tuned, the other layers remain non-qat, i.e, the full-precision/float32. Then the generated model will be a hybrid QAT one as a result, right?

**Comment by liamsun2019** [comment] 2021-12-20 07:51
I modified the description file of the quantized model as the way you suggested. The training goes normally while the final conversion to tflite fails with the following errors:

    converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/TinyNeuralNetwork-0.1.0+858a132143b7f4c6f3e1bfc95084a29e37ea8ef7-py3.6.egg/tinynn/converter/base.py", line 260, in convert
    self.init_jit_graph()
  File "/usr/local/lib/python3.6/dist-packages/TinyNeuralNetwork-0.1.0+858a132143b7f4c6f3e1bfc95084a29e37ea8ef7-py3.6.egg/tinynn/converter/base.py", line 79, in init_jit_graph
    script = torch.jit.trace(self.model, self.dummy_input)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "out/movenet_qat.py", line 182, in forward
    backbone_body_0_1 = self.backbone_body_0_1(backbone_body_0_0)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 725, in _call_impl
    result = self._slow_forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 709, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/quantized/modules/conv.py", line 332, in forward
    input, self._packed_params, self.scale, self.zero_point)
RuntimeError: Could not run 'quantized::conv2d.new' with arguments from the 'CPU' backend. 'quantized::conv2d.new' is only available for these backends: [QuantizedCPU, BackendSelect, Named, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, Tracer, Autocast, Batched, VmapMode].
[movenet_qat.zip](https://github.com/alibaba/TinyNeuralNetwork/files/7743416/movenet_qat.zip)

**Comment by dinghuanghao** [comment] 2021-12-20 08:22
config={'rewrite_graph': False}

**Comment by dinghuanghao** [comment] 2021-12-20 08:28
> 

Yes，operators outside the range of FakeQuant and FakeDequant will be float 32, and a mixed precision model will be generated after convert.

**Comment by liamsun2019** [comment] 2021-12-20 08:51
I set rewrite_graph=False after my modifications and the following error rises up during conversion:
  File "main.py", line 227, in main_quant
    converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/TinyNeuralNetwork-0.1.0+858a132143b7f4c6f3e1bfc95084a29e37ea8ef7-py3.6.egg/tinynn/converter/base.py", line 260, in convert
    self.init_jit_graph()
  File "/usr/local/lib/python3.6/dist-packages/TinyNeuralNetwork-0.1.0+858a132143b7f4c6f3e1bfc95084a29e37ea8ef7-py3.6.egg/tinynn/converter/base.py", line 79, in init_jit_graph
    script = torch.jit.trace(self.model, self.dummy_input)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
RuntimeError: Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.

The original model (before being quantized) does return a dictionary. But above error does not appear before my modifications to the quantized model description. No idea what's the root cause.

**Comment by dinghuanghao** [comment] 2021-12-20 09:40
Tomorrow I will upload a demo of mixed precision quantization :)

**Comment by dinghuanghao** [comment] 2021-12-21 03:55
The mixed precision QAT example has been added, please update to the latest tinynn.

**Comment by liamsun2019** [comment] 2021-12-21 03:56
Yes, I just updated and would try it out.

**Comment by liamsun2019** [comment] 2021-12-21 04:48
I modified my codes accordingly. But the same error still exists:
  File "main.py", line 227, in main_quant
    converter.convert()
  File "/usr/local/lib/python3.6/dist-packages/TinyNeuralNetwork-0.1.0+a60ddb1432bfd81eebd2d8d232e3a67bb6d2c434-py3.6.egg/tinynn/converter/base.py", line 260, in convert
    self.init_jit_graph()
  File "/usr/local/lib/python3.6/dist-packages/TinyNeuralNetwork-0.1.0+a60ddb1432bfd81eebd2d8d232e3a67bb6d2c434-py3.6.egg/tinynn/converter/base.py", line 79, in init_jit_graph
    script = torch.jit.trace(self.model, self.dummy_input)
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 742, in trace
    _module_class,
  File "/usr/local/lib/python3.6/dist-packages/torch/jit/_trace.py", line 940, in trace_module
    _force_outplace,
RuntimeError: Encountering a dict at the output of the tracer might cause the trace to be incorrect, this is only valid if the container structure does not change based on the module's inputs. Consider using a constant container instead (e.g. for `list`, use a `tuple` instead. for `dict`, use a `NamedTuple` instead). If you absolutely need this and know the side effects, pass strict=False to trace() to allow this behavior.

code snippet:
 fake_quant_0 = self.fake_quant_0(backbone_fpn_layer_blocks_0_conv_2)
 #hm_hp_0 = self.hm_hp_0(backbone_fpn_layer_blocks_0_conv_2)
 hm_hp_0 = self.hm_hp_0(fake_quant_0)
 hm_hp_1 = self.hm_hp_1(hm_hp_0)
 hm_hp_2 = self.hm_hp_2(hm_hp_1)
 hm_hp_3 = self.hm_hp_3(hm_hp_2)
 fake_dequant_0 = self.fake_dequant_0(hm_hp_3)

[movenet_qat.zip](https://github.com/alibaba/TinyNeuralNetwork/files/7749639/movenet_qat.zip)

**Comment by dinghuanghao** [comment] 2021-12-21 06:55
Please give me the original generated model file and the input shape.

**Comment by liamsun2019** [comment] 2021-12-21 07:01
FYR
[test.zip](https://github.com/alibaba/TinyNeuralNetwork/files/7750249/test.zip)

**Comment by dinghuanghao** [comment] 2021-12-21 07:01
Can you run exampl correctly?

**Comment by liamsun2019** [comment] 2021-12-21 07:02
Not yet. I can try that later.

**Comment by liamsun2019** [comment] 2021-12-22 01:29
As for the example, I have not tested it yet since I have no cifar10 dataset currently(I can download it anyway). I don't find out any fatal issues in my attached py script either. So I'm still unsure what's the possible reason for the conversion error.

**Comment by dinghuanghao** [comment] 2021-12-22 03:02
If you don’t have the cifar10 dataset, just use dummy_input to inference once.

**Comment by liamsun2019** [comment] 2021-12-23 00:52
I run the mixed qat example after some minor modification(path, batchsize etc.). The training goes well and the conversion is successful. Could you help point out any possible buggy codes in my attached file? I guess the big difference is that my model returns an output containing QAT and non-QAT while your model just returns QAT in your example.

**Comment by dinghuanghao** [comment] 2021-12-23 06:13
ok

**Comment by dinghuanghao** [comment] 2021-12-24 06:09
This is a bug caused by graph tracer, we will fix it soon

**Comment by liamsun2019** [comment] 2021-12-24 06:11
Thanks for quick feedback and look forward to your fix.

**Comment by peterjc123** [comment] 2021-12-24 07:35
@liamsun2019 A fix has been uploaded to remedy that. BTW, I updated the model description script for you. For arithmetic operations to happen in non-quantized computation graph, it is important to write them back to `torch.foo` variants from the `torch.quantization.FloatFunctional().foo` ones.
[movenet_qat.py.zip](https://github.com/alibaba/TinyNeuralNetwork/files/7773199/movenet_qat.py.zip)

**Closed** 2022-01-06 08:53 UTC
Labels: question
