### ISSUE TITLE
Concatenation has inconsistent input parameters quantization parameters

### ISSUE THREAD

**Issue by LynnL4** [alibaba/TinyNeuralNetwork#221] opened 2023-05-26 11:53 UTC
#### Bug
After quantization, there is a issue of inconsistency in the quantization parameters of the input parameters of concatenation.

#### Reproduce
https://raw.githubusercontent.com/LynnL4/Public/main/tinynn/yolodetector_q.py

#### Expectation
Conncation uses consistent quantization parameters for all inputs and outputs

**Comment by LynnL4** [comment] 2023-05-31 03:39
I tried to add a quantization operator below the nodes with different quantization parameters, and this solved the problem I encountered. But there are still some details that are not taken care of. 
https://github.com/LynnL4/TinyNeuralNetwork/commit/6f62020ae1b5a7ad5839e68fb3ec356c6a65c51d

**Comment by peterjc123** [comment] 2023-09-06 12:29
Looks like a duplicate of https://github.com/alibaba/TinyNeuralNetwork/issues/95#issuecomment-1183927442

**Comment by peterjc123** [comment] 2023-09-06 12:31
![image](https://github.com/alibaba/TinyNeuralNetwork/assets/9998726/1cdf7c4e-2d1b-4aa7-bb4f-7e7b853c0ada)
I think this part of the model should be quantized, not only because of this, but also there are something that cannot be quantized like `pow`.

**Comment by LynnL4** [comment] 2023-09-06 12:51
If not quantified, it would be unfriendly for devices like MCU, such as esp32s3. When exporting the YOLOv5 project to int8 TFLite, a quantization operator will also be added in this case. However, it is important to ensure that the values of the input tensor are within the same magnitude to avoid losing a significant amount of precision. Tomorrow, I will try exporting YOLOv8 to TFLite to see what the situation will be. The YOLOv8 project uses onnx2tf.

**Comment by peterjc123** [comment] 2023-09-06 16:16
> If not quantized, it would be unfriendly for devices like MCU, such as esp32s3.

Yes, but it seems the Pow op has Quantize and Dequantize ops around it, which is already not optimal. Even if https://github.com/alibaba/TinyNeuralNetwork/issues/95#issuecomment-1183927442 is resolved, we will add three more Quantize ops to perform re-quantization before the Concatenation op. Actually, I don't know how is the performance of the those ops using Float32 kernels.

> However, it is important to ensure that the values of the input tensor are within the same magnitude to avoid losing a significant amount of precision.
Yes, I agree with you.

> The YOLOv8 project uses onnx2tf.
I suppose they will add Quantize nodes before the Concatenation nodes, which may lead to the same result.

**Comment by peterjc123** [comment] 2023-09-20 03:48
Let's continue the discussion in #95.

**Closed by peterjc123** 2023-09-20 03:48 UTC
Labels: bug, duplicate, awaiting response
